module.exports.config = {
  name: "kontra",
  version: "1.0.0",
  role: 0,
  usePrefix: false,
  commandCategory: "fun",
  usages: "kontra",
  cooldowns: 3,
};

module.exports.run = async function ({ api, event }) {
  const { threadID, messageID } = event;

  const kontraReplies = [
    "Ang kapal din ng mukha mo para sabihin yan. Edi wow. ðŸ™„",
    "Tigilan mo nga 'yan, hindi ka nakakatawa. ðŸš«",
    "Hala, ang confident mo ah, pero wala namang sense. ðŸ’€",
    "Aba, ikaw na talaga. Feeling expert? Wala ka nga alam. ðŸ¤¡",
    "Ikaw? Tama? Hahaha, joke of the year ka talaga. ðŸ˜‚",
    "Grabe ka. Ang bigat ng sinabi mo, pero ang gaan ng utak mo. ðŸ§ âŒ",
    "Pashare naman ng kapal ng mukha mo, nauubusan na kasi ako. ðŸ˜’",
    "Alam mo, minsan ang tahimik mas okay kaya manahimik kang kupal ka. ðŸ”‡",
    "Ang galing mo ah, para kang tanga. ðŸ¤¦â€â™€ï¸",
    "Edi ikaw na matalino, kami na bobo. Pahinga ka na, girl/boy. ðŸ˜¤",
    "Patawad ha, pero wala ka talagang ambag. NEXT! ðŸ›‘",
    "Bakit ka ba nag-effort magsalita? Sayang laway mo eh. ðŸ’¦",
    "Ang lakas ng loob mong magsalita, pero wala namang connect. ðŸš®",
    "Ikaw yung tipo ng tao na pwedeng wala na lang. ðŸ˜‚",
    "Hala sige, ikaw na bida. Bida Bida ka naman. ðŸŽ­",
    "Tama ka? Charot! Never naman nangyari yun. ðŸ™ƒ",
    "Galing mo. Clap clap. Pero walang nakikinig. ðŸ‘",
    "Pwede bang magpahinga ka na? Napapagod na kami sa'yo. ðŸ¥±",
    "Wow, may sinabi ka. Pero sana tinago mo na lang. ðŸ¤",
    "Balita ko, ikaw daw yung perpektong example ng mali. ðŸ«¢",
    "Alam mo, sayang ang effort mo. Walang may pake. âŒ",
    "Galing mo pala. Totoo kaya? Charot. âœï¸",
    "Kung pagod ka na, bakit di ka pa tumigil? ðŸ™„",
    "Sa dami ng sinabi mo, wala namang kwenta. ðŸ—‘ï¸",
    "Gising ka ba? Kasi parang tulog utak mo. ðŸ˜µ",
    "Wow, ikaw na ang bida! Kaya lang, wala kang audience. ðŸŽ¬",
    "Ang ganda ng speech mo... sa utak mo lang. ðŸ¤¯",
    "Kung iniisip mo na matalino ka, isip ka ulit. ðŸ˜‚",
    "Alam mo, masaya ka pa ba? Parang hindi kita feel. ðŸ¤·â€â™€ï¸",
    "Ang confident mo ah. Sana madapa ka. ðŸ™ƒ",
    "Ang dami mong alam. Sayang, walang pumapansin. ðŸ§",
    "Kung si Batang Yagit may theme song, ikaw may 'Basura ng Taon.' ðŸ—‘ï¸",
    "Sana lang, next time may sense naman sinabi mo. ðŸ™",
    "Huwag kang mag-alala, ini-ignore ka namin. ðŸ˜Š",
    "Alam mo, may ibang planeta na bagay sa'yo. ðŸš€",
    "Kapag tumahimik ka, parang nagkaroon ng peace sa mundo. ðŸŒ",
    "Ang dami mong sinasabi pero wala naman nagtanong. ðŸ¤”",
    "Kung may contest ng sablay, panalo ka na agad. ðŸ†",
    "Huwag kang mag-alala, hindi ka namin papansinin. ðŸ™„",
    "Ang galing mo palang mang-bullsh*t. Apir! ðŸ™Œ",
    "Kung may bayad ang kausap, bankrupt na kami dahil sa'yo. ðŸ’¸",
    "Sa sobrang dami ng alam mo, wala pa ring nagbibilang. ðŸ˜…",
    "Kaya pala. Walang nagtanong. Bye! âœ‹",
    "Kung gusto mong magbida, humanap ka ng stage. Hindi dito. ðŸŽ¤",
    "Ikaw ang tunay na definition ng unnecessary. ðŸ’¯",
    "May utang ka pa sa mundo: ang tahimik mo. ðŸ¤«",
    "Kung may mali, sigurado ako na ikaw yun. ðŸ¤­",
    "Ikaw na matalino. Pero bakit parang sabaw ka pa rin? ðŸ¥£",
    "Balita ko, nawala utak mo. Hanap ka na lang bago ka magsalita. ðŸ”",
    "Ang talino mo! kaso walang may pake. ðŸ˜‚",
    "Kapag ikaw nagsalita, parang end of the world. ðŸŒ",
    "Ang galing mong mang-enganyo... ng mga walang pake. ðŸ‘",
    "Kung effort lang, panalo ka na. Sa sense? Zero ka pa rin. ðŸ¥‡",
    "Hala sige, ikaw na ang nagmamay-ari ng kawalan. ðŸ¤·",
    "Sana magpahinga ka muna. Napagod na kami sa'yo. ðŸ˜´",
    "Bakit ganyan ka? Para kang lagging warning sa buhay. ðŸš¨",
    "Kung papalitan kita ng sound effect, mas maganda siguro tahimik. ðŸ”‡",
    "Huwag kang magalala. Hindi ikaw ang pipiliin. ðŸ˜‚",
    "Wow, ang haba ng sinabi mo. Sana next time, may point. ðŸ“",
    "Kung may award sa kakornihan, panalo ka na. ðŸ†",
    "Kapag ikaw nagsalita, ang mundo parang naghinto. In shock kami. ðŸ˜µâ€ðŸ’«",
    "Ikaw ang hero ng boredom. Congrats! ðŸŽ­",
    "Sa sobrang unique mo, parang gusto mo na lang mawala. ðŸš®",
    "Ang lakas ng aura mo. Negative nga lang. ðŸ‘Ž",
    "Kung may replay button ang buhay, di ka namin uulit-ulitin. â®ï¸",
    "Pwede kang mag-take two? Kasi sa unang take, sablay ka na agad. ðŸŽ¬",
    "Wow, ikaw na ang huling tao na gusto naming makausap. ðŸ‘‹",
    "Kung si Bayani may ambag, ikaw ang taong 'walang bayag.' ðŸ«°",
    "Kapag ikaw nagsalita, para kang dictionary na mali lahat. ðŸ“–",
    "Huwag kang magtaka kung di ka pansinin. Natural lang yan. ðŸ˜",
    "Basta ikaw nagsalita, kami automatic off. ðŸ“´",
    "Ang kapal ng presensya mo, pero ang babaw ng laman. ðŸ™…",
    "Pwede bang pakiulit? Ah wag na pala. Huwag ka na magsalita. ðŸš«",
    "Ikaw ang example ng taong dapat pwedeng i-mute. ðŸ”‡",
    "Sige, bida ka. Kami na ang magko-comment. Edi wow. ðŸ‘",
    "Kung mag-effort ka, sana nasa ibang lugar. Hindi dito. ðŸ›‘",
    "Kapag ikaw ang topic, ang saya naming lumipat. ðŸ¤£",
    "Ikaw ang tunay na dahilan kung bakit may 'skip' button. ðŸŽµ"
  ];

  // Random kontra response
  const randomReply = kontraReplies[Math.floor(Math.random() * kontraReplies.length)];

  // Send the kontra response
  return api.sendMessage(randomReply, threadID, messageID);
};